pull_request_title: Update Translation
commit_message: '[ci skip]'
files:
  - source: /languages/template.pot
    translation: /languages/%two_letters_code%.po
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        zh-CN: zh_CN
        zh-TW: zh_TW
